version: '3.8'
services:
  mysqlserver:
    platform: linux/amd64
    image: mysql:5.7
    env_file:
      - ./mysql.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - '5306:3306'

volumes:
  dbdata:
    driver: local
